### ISSUE TITLE
implement backend 

### ISSUE THREAD

**Issue by sanjai0py** [hkirat/leetcode-clone#23]
enough of the frontend please implement backend logic. "leetcode back-end development" is views worthy.

**Comment by ankush109** [comment]
sabar karo

**Comment by khazaddoom** [comment]
> enough of the frontend please implement backend logic. "leetcode back-end development" is views worthy.

interested in doing it? i am happy to contribute. what say?

**Comment by sanjai0py** [comment]
@khazaddoom i am interested! but i don't know where to start.

**Comment by khazaddoom** [comment]
> @khazaddoom i am interested! but i don't know where to start.

We can take an approach similar to how [Judge0](https://judge0.com/) does. They have a sync way in which you submit code and on the REST api response you get code output or errors. Also an Async way in which you submit the code and then keep polling or regular intervals to check if the result is available.

**Comment by sanjai0py** [comment]
@khazaddoom that sounds great!
